name: Google Indexing API Notify

on:
  repository_dispatch:
    types: [index_request]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_KEY_JSON }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Notify Google
        run: |
          # トークンの取得と通知の実行
          TOKEN=$(gcloud auth print-access-token)
          URL="${{ github.event.client_payload.url }}"
          
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $TOKEN" \
            -d "{\"url\": \"$URL\", \"type\": \"URL_UPDATED\"}" \
            "https://indexing.googleapis.com/v3/urlNotifications:publish"
